name: play_GW-environment
channels:
    - conda-forge
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - jupyterlab
  - IPython
  - ipywidgets
  - h5py
  - ffmpeg
  - gwsurrogate
  - pip
  - pip:
    - NRSur7dq2
    - notebook
