name: play_GW-environment
channels:
    - conda-forge
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - jupyterlab
  - IPython
  - ipywidgets
  - ipykernel
  - nbformat
  - line_profiler
  - memory_profiler
  - nb_conda_kernels
  - h5py
  - gwsurrogate
  - pip
  - jupyterlab
  - mpl-interactions
  - ipympl
  - jupyter_contrib_nbextensions
  - pip:
    - NRSur7dq2
    - notebook
